name: Build app and deploy to aliyun
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - master
jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: Checkout
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@master
      # 安装Node13
      - name: use Node.js 16.13.1
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      # 安装依赖
      - name: npm  install
        run: npm install
      # 打包
      - name: npm run build
        run: npm run build
      # 部署
      - name: FTP Deployer
        uses: sand4rt/ftp-deployer@v1.3
        with:
          sftp: false # optional
          host: ${{ secrets.FTP_HOST }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
          port: 21 # optional, default is: 21
          username: ${{ secrets.FTP_USERNAME }} # FTP username
          password: ${{ secrets.FTP_PASSWORD }} # FTP password
          remote_folder: ${{ secrets.FTP_REMOTE_FOLDER }} # optional, remote path of your FTP server
          local_folder: './dist' # optional, local path, default is: dist
          cleanup: false # optional, remove existing files inside FTP remote folder
          # include: ['./dist'] # optional, e.g. ['dist']
          # exclude: ['node_modules/**'] # optional, e.g. ['node_modules/**', '.git/**', '*.env']
          pasive: false # optional
      # - name: FTP Deployer Aliyun
      #   uses: sand4rt/ftp-deployer@v1.3
      #   with:
      #     sftp: false # optional
      #     host: ${{ secrets.FTP_HOST }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
      #     port: 21 # optional, default is: 21
      #     username: ${{ secrets.FTP_USERNAME }} # FTP username
      #     password: ${{ secrets.FTP_PASSWORD }} # FTP password
      #     remote_folder: ${{ secrets.FTP_REMOTE_FOLDER }} # optional, remote path of your FTP server
      #     local_folder: dist # optional, local path, default is: dist
      #     cleanup: false # optional, remove existing files inside FTP remote folder
      #     pasive: true # optional
      # 部署到阿里云
      # - name: Deploy to Aliyun
      #   uses: easingthemes/ssh-deploy@v2.1.1
      #   env:
      #     # 私钥
      #     SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      #     # scp参数
      #     ARGS: '-avzr --delete'
      #     # 源目录，编译后生成的文件目录
      #     SOURCE: './dist'
      #     # 服务器ip：换成你的服务器IP
      #     REMOTE_HOST: '47.106.141.235'
      #     # 用户
      #     REMOTE_USER: 'root'
      #     # 目标地址 你在服务器上部署代码的地方
      #     TARGET: '/root/web/vue-drag-demo'
