name: Build app and deploy to aliyun
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - master
jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: Checkout
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@v2
      # 安装Node13
      - name: use Node.js 16.13.1
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      # 安装依赖
      - name: npm  install
        run: npm install
      # 打包
      - name: npm run build
        run: npm run build
      # 部署
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './dist/'
          server-dir: ${{ secrets.FTP_REMOTE_FOLDER }}
# 同步代码到gitee          
#       - name: Mirror the Github organization repos to Gitee.
#         uses: Yikun/hub-mirror-action@master
#         with:
#           src: github/kunpengcompute
#           dst: gitee/kunpengcompute
#           dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
#           dst_token: ${{ secrets.GITEE_TOKEN }}
#           account_type: org
        # src_account_type: org
        # dst_account_type: org    
      # - name: Deploy to Aliyun
      #   uses: easingthemes/ssh-deploy@v2.1.1
      #   env:
      #     # 私钥
      #     SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      #     # scp参数
      #     ARGS: '-avzr --delete'
      #     # 源目录，编译后生成的文件目录
      #     SOURCE: './dist'
      #     # 服务器ip：换成你的服务器IP
      #     REMOTE_HOST: '47.106.141.235'
      #     # 用户
      #     REMOTE_USER: 'root'
      #     # 目标地址 你在服务器上部署代码的地方
      #     TARGET: '/root/web/vue-drag-demo'
